export const QUESTION_MAPPING_AVALIA = {
  discente: {
    autoavaliacao: {
      '1.1.1': 'Organizei meus estudos com base no Plano de Ensino (Programação) da Disciplina/do Módulo.',
      '1.1.2': 'Mantive um relacionamento cordial com o/a professor/a.',
      '1.1.3': 'Frequentei as aulas/atividades conforme programadas.',
      '1.1.4': 'Aprendi os conteúdos ministrados na Disciplina/no Módulo.',
      '1.1.5': 'Estive motivado/a ao longo das atividades propostas na Disciplina/no Módulo.',
      '1.1.6': 'Aprofundei meus conhecimentos, de maneira autônoma, com diferentes fontes de estudos, fora da sala de aula.',
      '1.1.7': 'Realizei as atividades da Disciplina/do Módulo atendendo aos prazos e critérios estabelecidos.',
    },
    atitude: {
      '2.1.1': 'O/A Docente foi assíduo/a às aulas.',
      '2.1.2': 'O/A Docente cumpriu o horário das aulas na forma prevista no Plano de Ensino (Programação).',
      '2.1.3': 'O/A Docente mostrou-se disponível para atender e orientar os/as estudantes quando solicitado.',
      '2.1.4': 'O/A Docente interagiu com a turma com ética e respeito.',
    },
    gestao: {
      '2.2.1': 'O/A Docente apresentou o Plano de Ensino (Programação) da Disciplina/do Módulo de acordo com a ementa.',
      '2.2.2': 'O/A Docente executou a programação prevista no Plano de Ensino (Programação) da Disciplina/Módulo.',
      '2.2.3': 'O/A Docente demonstrou domínio dos conhecimentos clássicos e/ou atualizados abordados na Disciplina/no Módulo.',
      '2.2.4': 'O/A Docente ensinou de forma problematizadora e contextualizada, com linguagem clara e objetiva.',
      '2.2.5': 'O/A Docente estimulou a turma a construir o interesse, a participação e a autonomia dos/as estudantes em relação ao conteúdo.',
      '2.2.6': 'O/A Docente contextualizou a Disciplina/Módulo no processo de formação cidadã e profissional.',
      '2.2.7': 'O/A Docente utilizou metodologias que atendem ao desenvolvimento de conteúdos, das estratégias de aprendizagem e da autonomia do/a discente.',
      '2.2.8': 'O/A Docente utilizou Tecnologias Digitais da Informação e Comunicação (TDIC) nas aulas/atividades.',
    },
    processo: {
      '2.3.1': 'O/A Docente explicou de forma objetiva o processo avaliativo da Disciplina/Módulo.',
      '2.3.2': 'O/A Docente avaliou a aprendizagem com critérios definidos de forma objetiva.',
      '2.3.3': 'O/A Docente avaliou a aprendizagem de acordo com o nível de profundidade dos conteúdos trabalhados na Disciplina/Módulo.',
      '2.3.4': 'O/A Docente utilizou diferentes instrumentos de avaliação (provas, seminários, produção textual, entre outros).',
    },
    instalacoes: {
      '3.1.1': 'As salas de aula e os mobiliários atenderam às necessidades do ensino no âmbito da Disciplina/Módulo.',
      '3.1.2': 'A infraestrutura das bibliotecas e as referências bibliográficas atenderam às necessidades do ensino no âmbito da Disciplina/Módulo.',
      '3.1.3': 'Os recursos audiovisuais atenderam às necessidades do ensino no âmbito da Disciplina/Módulo.',
      '3.1.4': 'Os recursos de informática atenderam às necessidades do ensino no âmbito da Disciplina/Módulo.',
    },
  },
  docente: {
    avaliacaoTurma: {
      '1.1.1': 'Os/As discentes organizaram seus estudos com base no Plano de Ensino (Programação) da Disciplina/do Módulo.',
      '1.1.2': 'Os/As discentes mantiveram um relacionamento cordial com o/a professor/a.',
      '1.1.3': 'Os/As discentes frequentaram as aulas/atividades conforme programado.',
      '1.1.4': 'Os/As discentes aprenderam os conteúdos ministrados na Disciplina/do Módulo.',
      '1.1.5': 'Os/As discentes estiveram motivados/as ao longo das atividades propostas na Disciplina/no Módulo.',
      '1.1.6': 'Os/As discentes aprofundaram seus conhecimentos, de maneira autônoma, com diferentes fontes de estudos, fora da sala de aula.',
      '1.1.7': 'Os/As discentes realizaram as atividades da Disciplina/do Módulo atendendo aos prazos e critérios estabelecidos.',
    },
    atitude: {
      '2.1.1': 'Fui assíduo/a às aulas.',
      '2.1.2': 'Cumpri o horário das aulas na forma prevista no Plano de Ensino (Programação).',
      '2.1.3': 'Mostrei-me disponível para atender e orientar os/as estudantes quando solicitado.',
      '2.1.4': 'Interagi com a turma com ética e respeito.',
    },
    gestao: {
      '2.2.1': 'Apresentei o Plano de Ensino (Programação) da Disciplina/Módulo de acordo com a ementa.',
      '2.2.2': 'Executei a programação prevista no Plano de Ensino (Programação) da Disciplina/Módulo.',
      '2.2.3': 'Demonstrei domínio de conhecimentos clássicos e/ou atualizados abordados na Disciplina/Módulo.',
      '2.2.4': 'Ensinei de forma problematizadora e contextualizada, com linguagem clara e objetiva.',
      '2.2.5': 'Estimulei o interesse, a participação e a autonomia dos/as estudantes em relação ao conteúdo.',
      '2.2.6': 'Contextualizei a Disciplina/Módulo no processo de formação cidadã e profissional.',
      '2.2.7': 'Utilizei metodologias que atendem ao desenvolvimento de conteúdos, das estratégias de aprendizagem e da autonomia do/a discente.',
      '2.2.8': 'Utilizei Tecnologias Digitais da Informação e Comunicação (TDIC) nas aulas/atividades.',
    },
    processo: {
      '2.3.1': 'Expliquei de forma objetiva o processo avaliativo da Disciplina/Módulo.',
      '2.3.2': 'Avaliei a aprendizagem com critérios definidos de forma objetiva.',
      '2.3.3': 'Avaliei a aprendizagem de acordo com o nível de profundidade dos conteúdos trabalhados na Disciplina/Módulo.',
      '2.3.4': 'Utilizei diferentes instrumentos de avaliação (provas, seminários, produção textual, entre outros).',
    },
    instalacoes: {
      '3.1.1': 'As salas de aula e os mobiliários atenderam as necessidades do ensino no âmbito da Disciplina/Módulo.',
      '3.1.2': 'A infraestrutura das bibliotecas e as referências bibliográficas atenderam as necessidades do ensino no âmbito da Disciplina/Módulo.',
      '3.1.3': 'Os recursos audiovisuais atenderam as necessidades do ensino no âmbito da Disciplina/Módulo.',
      '3.1.4': 'Os recursos de informática atenderam as necessidades do ensino no âmbito da Disciplina/Módulo.',
    },
  },
};
